apiVersion: v1
kind: Namespace
metadata:
  name: virgocoder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: virgocoder
  name: feishubot
  labels:
    app: feishubot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feishubot
  template:
    metadata:
      labels:
        app: feishubot
    spec:
      containers:
        - name: feishubot
          image: registry.cn-shenzhen.aliyuncs.com/virgocoder/feishubot:v0.1.1
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: TZ
              value: "Asia/Shanghai"
            - name: ZONEINFO
              value: /root/time/zoneinfo.zip
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  namespace: virgocoder
  name: feishubot-service
spec:
  selector:
    app: feishubot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: virgocoder
  name: feishubot-ingress
spec:
  rules:
    - host: api.gianttough.cn
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: feishubot-service
                port:
                  number: 80
